import type { Manifest } from "../types/manifest.ts";
import { readManifest, getManifestPath } from "../core/manifest.ts";
import path from "node:path";
import { resolveApiKey, writeConfig, readConfig } from "../core/config.ts";
import { normalizeFormat, exportToFormat } from "../core/export.ts";
import { ask, askYesNo } from "../core/prompt.ts";
import { generateResume } from "../core/llm.ts";
import { buildVerificationBlock } from "../core/verification.ts";

export function renderResume(manifest: Manifest): string {
  const skills = [...manifest.skills].sort((a, b) => b.confidence - a.confidence);
  const commitCount = manifest.evidence.filter((e) => e.type === "commit").length;
  const depCount = manifest.evidence.filter((e) => e.type === "dependency").length;
  const configCount = manifest.evidence.filter((e) => e.type === "config").length;

  let md = `# ${manifest.author.name}\n\n`;
  md += `> Verifiable Developer Resume — generated ${manifest.generated_at}\n\n`;
  md += `## Skills\n\n`;

  for (const skill of skills) {
    md += `### ${skill.name}\n`;
    md += `- **Confidence:** ${skill.confidence}\n`;
    md += `- **Evidence:** ${skill.evidence_ids.join(" ")}\n`;
    md += `- **Inferred by:** ${skill.inferred_by}\n\n`;
  }

  md += `## Evidence Summary\n\n`;
  md += `- **Total evidence items:** ${manifest.evidence.length}\n`;
  md += `- **Commits analyzed:** ${commitCount}\n`;
  md += `- **Dependencies detected:** ${depCount}\n`;
  md += `- **Config files scanned:** ${configCount}\n\n`;
  md += `---\n\n`;
  md += `*This resume was generated by VeriResume and can be cryptographically verified.*\n`;
  md += `*Repo: ${manifest.repo.url || "local"} @ ${manifest.repo.head_commit}*\n`;

  return md;
}

async function resolveApiKeyInteractive(cwd: string): Promise<string> {
  let apiKey = await resolveApiKey(cwd);

  if (!apiKey) {
    console.log("No API key found.");
    apiKey = await ask("Enter your Anthropic API key: ");
    if (!apiKey) {
      throw new Error("API key is required for locale-aware rendering.");
    }
    const save = await askYesNo("Save to .veriresume/config.json for future use?");
    if (save) {
      const config = await readConfig(cwd);
      config.anthropic_api_key = apiKey;
      await writeConfig(cwd, config);
      console.log("Key saved.");
    }
  }

  return apiKey;
}

export async function runRender(
  cwd: string,
  locale?: string,
  format?: string,
  output?: string,
): Promise<void> {
  const manifestPath = getManifestPath(cwd);
  const manifest = await readManifest(manifestPath);

  if (!locale) {
    const md = renderResume(manifest);
    const fmt = normalizeFormat(format || "md");
    const outputPath = output || path.join(cwd, `resume.${fmt === "jpeg" ? "jpg" : fmt}`);
    await exportToFormat(md, fmt, outputPath);
    console.log(`Resume written to ${outputPath}`);
    return;
  }

  const apiKey = await resolveApiKeyInteractive(cwd);

  const personalInfoResponse = await ask(
    "Would you like to include a personal introduction or work experience?\n(Type your info, or 'skip' to continue): "
  );
  const personalInfo = personalInfoResponse.toLowerCase() === "skip" ? null : personalInfoResponse || null;

  console.log(`Generating resume in ${locale}...`);
  let resumeContent: string;
  try {
    resumeContent = await generateResume(apiKey, manifest, locale, personalInfo);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    if (message.includes("401") || message.toLowerCase().includes("auth")) {
      throw new Error("Invalid API key. Check your ANTHROPIC_API_KEY or run render again to re-enter it.");
    }
    throw new Error(`Resume generation failed: ${message}`);
  }
  const verificationBlock = buildVerificationBlock(manifest);
  const fullResume = resumeContent + verificationBlock;

  const fmt = normalizeFormat(format || "md");
  const outputPath = output || path.join(cwd, `resume.${fmt === "jpeg" ? "jpg" : fmt}`);
  await exportToFormat(fullResume, fmt, outputPath);
  console.log(`Resume written to ${outputPath}`);
}
