import type { Manifest } from "../types/manifest.ts";
import { readManifest, getManifestPath } from "../core/manifest.ts";
import path from "node:path";
import { resolveApiKey, writeConfig, readConfig } from "../core/config.ts";
import { normalizeFormat, exportToFormat } from "../core/export.ts";
import { ask, askYesNo } from "../core/prompt.ts";
import { generateResume } from "../core/llm.ts";
import { buildVerificationBlock } from "../core/verification.ts";

export interface RenderOptions {
  apiKey?: string;
  personalInfo?: string;
  yes?: boolean;
  displayName?: string;
  contactEmail?: string;
}

export interface ResumeDisplayOptions {
  displayName?: string;
  contactEmail?: string;
}

export function renderResume(manifest: Manifest, display?: ResumeDisplayOptions): string {
  const skills = [...manifest.skills].sort((a, b) => b.confidence - a.confidence);
  const commitCount = manifest.evidence.filter((e) => e.type === "commit").length;
  const depCount = manifest.evidence.filter((e) => e.type === "dependency").length;
  const configCount = manifest.evidence.filter((e) => e.type === "config").length;

  const name = display?.displayName || manifest.author.name;
  let md = `# ${name}\n\n`;
  if (display?.contactEmail) {
    md += `**Email:** ${display.contactEmail}\n\n`;
  }
  md += `> Verifiable Developer Resume — generated ${manifest.generated_at}\n\n`;
  md += `## Skills\n\n`;

  for (const skill of skills) {
    const decision = skill.review_decision ?? (skill.inferred_by === "llm" ? "llm-reviewed" : "static-only");
    md += `### ${skill.name}\n`;
    md += `- **Confidence:** ${skill.confidence}`;
    if (decision === "static-only") {
      md += ` (static-only)\n`;
    } else {
      md += ` (reviewed)\n`;
    }
    md += `- **Evidence:** ${skill.evidence_ids.join(" ")}\n`;
    // Only show strengths for LLM-reviewed skills
    if (decision !== "static-only" && skill.strengths && skill.strengths.length > 0) {
      md += `- **Strengths:**\n`;
      for (const s of skill.strengths) {
        md += `  - ${s}\n`;
      }
    }
    md += `\n`;
  }

  md += `## Evidence Summary\n\n`;
  md += `- **Total evidence items:** ${manifest.evidence.length}\n`;
  md += `- **Commits analyzed:** ${commitCount}\n`;
  md += `- **Dependencies detected:** ${depCount}\n`;
  md += `- **Config files scanned:** ${configCount}\n\n`;
  md += `---\n\n`;
  md += `*This resume was generated by SkillProof and can be cryptographically verified.*\n`;
  md += `*Repo: ${manifest.repo.url || "local"} @ ${manifest.repo.head_commit}*\n`;

  return md;
}

async function resolveApiKeyInteractive(cwd: string): Promise<string> {
  let apiKey = await resolveApiKey(cwd);

  if (!apiKey) {
    console.log("No API key found.");
    apiKey = await ask("Enter your Anthropic API key: ");
    if (!apiKey) {
      throw new Error("API key is required for locale-aware rendering.");
    }
    const save = await askYesNo("Save to .skillproof/config.json for future use?");
    if (save) {
      const config = await readConfig(cwd);
      config.anthropic_api_key = apiKey;
      await writeConfig(cwd, config);
      console.log("Key saved.");
    }
  }

  return apiKey;
}

export async function runRender(
  cwd: string,
  locale?: string,
  format?: string,
  output?: string,
  options?: RenderOptions,
): Promise<void> {
  const manifestPath = getManifestPath(cwd);
  const manifest = await readManifest(manifestPath);

  // Resolve display name and contact email
  let displayName = options?.displayName;
  let contactEmail = options?.contactEmail;
  if (!options?.yes && displayName === undefined) {
    const nameAnswer = await ask(`Display name for resume (default: ${manifest.author.name}): `);
    displayName = nameAnswer || undefined;
  }
  if (!options?.yes && contactEmail === undefined) {
    const emailAnswer = await ask(`Contact email for resume (default: ${manifest.author.email}): `);
    contactEmail = emailAnswer || undefined;
  }
  const display: ResumeDisplayOptions = { displayName, contactEmail };

  if (!locale) {
    const md = renderResume(manifest, display);
    const fmt = normalizeFormat(format || "md");
    const outputPath = output || path.join(cwd, `resume.${fmt === "jpeg" ? "jpg" : fmt}`);
    await exportToFormat(md, fmt, outputPath);
    console.log(`Resume written to ${outputPath}`);
    return;
  }

  const apiKey = options?.apiKey || await resolveApiKeyInteractive(cwd);

  let personalInfo: string | null = null;
  if (options?.personalInfo !== undefined) {
    personalInfo = options.personalInfo || null;
  } else if (!options?.yes) {
    const personalInfoResponse = await ask(
      "Would you like to include a personal introduction or work experience?\n(Type your info, or 'skip' to continue): "
    );
    personalInfo = personalInfoResponse.toLowerCase() === "skip" ? null : personalInfoResponse || null;
  }

  console.log(`Generating resume in ${locale}...`);
  let resumeContent: string;
  try {
    resumeContent = await generateResume(apiKey, manifest, locale, personalInfo, display);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    if (message.includes("401") || message.toLowerCase().includes("auth")) {
      throw new Error("Invalid API key. Check your ANTHROPIC_API_KEY or run render again to re-enter it.");
    }
    throw new Error(`Resume generation failed: ${message}`);
  }
  const verificationBlock = buildVerificationBlock(manifest);
  const fullResume = resumeContent + verificationBlock;

  const fmt = normalizeFormat(format || "md");
  const outputPath = output || path.join(cwd, `resume.${fmt === "jpeg" ? "jpg" : fmt}`);
  await exportToFormat(fullResume, fmt, outputPath);
  console.log(`Resume written to ${outputPath}`);
}
